/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import static halaqat_honien.Halaqat_Honien.*;



public class MainPage extends javax.swing.JFrame {
    
  
    
    /**
     * Creates new form mainPage
     */
    public MainPage() {
        initComponents();
    }

  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allTeachersBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        allStudentsBtn = new javax.swing.JButton();
        addTeacherBtn = new javax.swing.JButton();
        updateTeacherBtn = new javax.swing.JButton();
        deleteTeacherBtn = new javax.swing.JButton();
        deletedStudentsBtn = new javax.swing.JButton();
        deletedStudentsBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setEnabled(false);
        setSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        allTeachersBtn.setBackground(new java.awt.Color(255, 255, 255));
        allTeachersBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        allTeachersBtn.setText("استعراض جميع المدرسين");
        allTeachersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTeachersBtnActionPerformed(evt);
            }
        });
        getContentPane().add(allTeachersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 500, 410, 80));

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        addBtn.setText("إضافة طالب");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 420, 80));

        updateBtn.setBackground(new java.awt.Color(255, 255, 255));
        updateBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        updateBtn.setText("تحديث بيانات طالب");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 420, 80));

        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        deleteBtn.setText("حذف طالب");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 420, 80));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/back-icon(2).png"))); // NOI18N
        backBtn.setText("رجوع   ");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 760, 185, 56));

        allStudentsBtn.setBackground(new java.awt.Color(255, 255, 255));
        allStudentsBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        allStudentsBtn.setText("استعراض جميع الطلاب");
        allStudentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudentsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(allStudentsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 420, 80));

        addTeacherBtn.setBackground(new java.awt.Color(255, 255, 255));
        addTeacherBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        addTeacherBtn.setText("إضافة مدرس");
        addTeacherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addTeacherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 410, 80));

        updateTeacherBtn.setBackground(new java.awt.Color(255, 255, 255));
        updateTeacherBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        updateTeacherBtn.setText("تحديث بيانات مدرس");
        updateTeacherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTeacherBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateTeacherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 410, 80));

        deleteTeacherBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteTeacherBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        deleteTeacherBtn.setText("حذف مدرس");
        deleteTeacherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTeacherBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteTeacherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, 410, 80));

        deletedStudentsBtn.setBackground(new java.awt.Color(255, 255, 255));
        deletedStudentsBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        deletedStudentsBtn.setText("أرشيف المدرسين المحذوفين");
        deletedStudentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedStudentsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deletedStudentsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 620, 410, 80));

        deletedStudentsBtn1.setBackground(new java.awt.Color(255, 255, 255));
        deletedStudentsBtn1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        deletedStudentsBtn1.setText("أرشيف الطلاب المحذوفين");
        deletedStudentsBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedStudentsBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(deletedStudentsBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 420, 80));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/shutterstock_75809713.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
           
        insertPage.setVisible(true);
        mainPage.setVisible(false);
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        updatePage.setVisible(true);
        mainPage.setVisible(false);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        deletePage.setVisible(true);
        mainPage.setVisible(false);           
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        loginPage.setVisible(true);  
        mainPage.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void allStudentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudentsBtnActionPerformed
        
        allStudentsPage.setVisible(true);
        mainPage.setVisible(false);
    }//GEN-LAST:event_allStudentsBtnActionPerformed

    private void allTeachersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTeachersBtnActionPerformed
        allTeachersPage.setVisible(true);
        mainPage.setVisible(false);
    }//GEN-LAST:event_allTeachersBtnActionPerformed

    private void addTeacherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherBtnActionPerformed
        
        insertTeacherPage.setVisible(true);
        mainPage.setVisible(false);
    }//GEN-LAST:event_addTeacherBtnActionPerformed

    private void deleteTeacherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTeacherBtnActionPerformed
        
        deleteTeacherPage.setVisible(true);
        mainPage.setVisible(false);   
    }//GEN-LAST:event_deleteTeacherBtnActionPerformed

    private void updateTeacherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTeacherBtnActionPerformed
        
        updateTeacherPage.setVisible(true);
        mainPage.setVisible(false);   
    }//GEN-LAST:event_updateTeacherBtnActionPerformed

    private void deletedStudentsBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedStudentsBtn1ActionPerformed
        
        
        allDeletedStudentsPage.setVisible(true);
        mainPage.setVisible(false);   
    }//GEN-LAST:event_deletedStudentsBtn1ActionPerformed

    private void deletedStudentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedStudentsBtnActionPerformed
        
        allDeletedTeachersPage.setVisible(true);
        mainPage.setVisible(false);  
    }//GEN-LAST:event_deletedStudentsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addTeacherBtn;
    private javax.swing.JButton allStudentsBtn;
    private javax.swing.JButton allTeachersBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteTeacherBtn;
    private javax.swing.JButton deletedStudentsBtn;
    private javax.swing.JButton deletedStudentsBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateTeacherBtn;
    // End of variables declaration//GEN-END:variables
}
