/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import static halaqat_honien.Halaqat_Honien.*;

/**
 *
 * @author Abdul
 */
public class SubMainPage extends javax.swing.JFrame {

    /**
     * Creates new form SubMainPage
     */
    public SubMainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        allStudentsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        deletedStudentsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        addBtn.setText("إضافة طالب    ");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 480, 80));

        updateBtn.setBackground(new java.awt.Color(255, 255, 255));
        updateBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        updateBtn.setText("تحديث بيانات طالب");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 480, 80));

        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        deleteBtn.setText("حذف طالب    ");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 480, 80));

        allStudentsBtn.setBackground(new java.awt.Color(255, 255, 255));
        allStudentsBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        allStudentsBtn.setText("استعراض جميع الطلاب");
        allStudentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudentsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(allStudentsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 480, 80));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/back-icon(2).png"))); // NOI18N
        backBtn.setText("رجوع   ");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 740, 185, 56));

        deletedStudentsBtn.setBackground(new java.awt.Color(255, 255, 255));
        deletedStudentsBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        deletedStudentsBtn.setText("أرشيف الطلاب المحذوفين");
        deletedStudentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedStudentsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deletedStudentsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 480, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/shutterstock_75809713.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

        insertPage.setVisible(true);
        subMainPage.setVisible(false);
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        updatePage.setVisible(true);
        subMainPage.setVisible(false);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        deletePage.setVisible(true);
        subMainPage.setVisible(false);

    }//GEN-LAST:event_deleteBtnActionPerformed

    private void allStudentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudentsBtnActionPerformed

        allStudentsPage.setVisible(true);
        subMainPage.setVisible(false);
    }//GEN-LAST:event_allStudentsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        loginPage.setVisible(true);
        subMainPage.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void deletedStudentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedStudentsBtnActionPerformed
             
        allDeletedStudentsPage.setVisible(true);
        subMainPage.setVisible(false);   
    }//GEN-LAST:event_deletedStudentsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton allStudentsBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deletedStudentsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
